[package]
name = "zw_stats_app"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
plotters = "0.3"
raylib = "5.0.2"
uuid = { version = "1.3", features = ["v4"] }

